baseURL = "https://thelondoncoder.com/"
languageCode = "en-gb"
title = "The London Coder"
theme = "londoncoder"
googleAnalytics = "G-CPMJL6FH62"

[params]
  description = "Senior Software Developer based in Central London, UK."
  author = "The London Coder"
  tagline = "software developer"

  [[params.projects]]
    name = "My Coding Blog"
    description = "My insights into Programming Languages, Distributed Systems, Unit Testing & Cloud Computing!"
    url = "https://simongilbert.net"
    tags = ["Websites", "Mobile Apps", "Cloud Computing"]

  [[params.projects]]
    name = "UK FIRE Calculator"
    description = "Helping you visualise and plan your FIRE journey to early retirement."
    url = "https://www.ukfirecalculator.com"
    tags = ["FIRE", "Early Retirement", "UK"]

  [[params.projects]]
    name = "Get Rich, Tax Free"
    description = "A UK Financial advice guide website."
    url = "https://www.getrichtaxfree.com"
    tags = ["UK", "Financial Advice", "HMRC"]

  [[params.projects]]
    name = "Lossless Image Compression"
    description = "A lossless image compression website, where image quality is retained."
    url = "https://www.compressanimage.com"
    tags = ["Lossless", "Image Compression"]

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/sahgilbert"
    icon = "github"
